### ISSUE TITLE
（小白提问）npm run dev报CopyWebpackPlugin错误，百度的加pattern试过了不行

### ISSUE THREAD

**Issue by qq715436512** [macrozheng/mall-admin-web#128]
C:\Users\Administrator\Desktop\mall-admin-web>npm run dev

> mall-admin-web@1.0.0 dev C:\Users\Administrator\Desktop\mall-admin-web
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

C:\Users\Administrator\Desktop\mall-admin-web\node_modules\copy-webpack-plugin\node_modules\schema-utils\dist\validate.js:105
    throw new _ValidationError.default(errors, schema, configuration);
    ^

ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options.patterns[0] has an unknown property 'ignore'. These properties are valid:
   object { from, to?, context?, globOptions?, filter?, transformAll?, toType?, force?, priority?, info?, transform?, transformPath?, noErrorOnMissing? }
    at validate (C:\Users\Administrator\Desktop\mall-admin-web\node_modules\copy-webpack-plugin\node_modules\schema-utils\dist\validate.js:105:11)
    at new CopyPlugin (C:\Users\Administrator\Desktop\mall-admin-web\node_modules\copy-webpack-plugin\dist\index.js:38:31)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\mall-admin-web\build\webpack.dev.conf.js:61:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at requireConfig (C:\Users\Administrator\Desktop\mall-admin-web\node_modules\webpack\bin\convert-argv.js:97:18)
    at C:\Users\Administrator\Desktop\mall-admin-web\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\Administrator\Desktop\mall-admin-web\node_modules\webpack\bin\convert-argv.js:102:15)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\mall-admin-web\node_modules\webpack-dev-server\bin\webpack-dev-server.js:224:50)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10) {
  errors: [
    {
      keyword: 'anyOf',
      dataPath: '.patterns[0]',
      schemaPath: '#/properties/patterns/items/anyOf',
      params: {},
      message: 'should match some schema in anyOf',
      schema: [Array],
      parentSchema: [Object],
      data: [Object],
      children: [Array]
    }
  ],
  schema: {
    definitions: { ObjectPattern: [Object], StringPattern: [Object] },
    type: 'object',
    additionalProperties: false,
    properties: { patterns: [Object], options: [Object] },
    required: [ 'patterns' ]
  },
  headerName: 'Copy Plugin',
  baseDataPath: 'options',
  postFormatter: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mall-admin-web@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mall-admin-web@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-10-07T10_57_58_397Z-debug.log

**Comment by qq715436512** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
