### ISSUE TITLE
npm install 安装报错

### ISSUE THREAD

**Issue by kyne0116** [macrozheng/mall-admin-web#16]
E:\01_Work\mall-admin-web>npm install
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
npm ERR! registry error parsing json
npm WARN prefer global node-gyp@3.8.0 should be installed with -g

> node-sass@4.11.0 install E:\01_Work\mall-admin-web\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-48_binding.node":

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> uglifyjs-webpack-plugin@0.4.6 postinstall E:\01_Work\mall-admin-web\node_modules\webpack\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.11.0 postinstall E:\01_Work\mall-admin-web\node_modules\node-sass
> node scripts/build.js

Building: E:\01_Work\01_DevSpace\nodes\nodejs\node.exe E:\01_Work\mall-admin-web\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'E:\\01_Work\\01_DevSpace\\nodes\\nodejs\\node.exe',
gyp verb cli   'E:\\01_Work\\mall-admin-web\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@6.9.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\01_Work\mall-admin-web\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\01_Work\mall-admin-web\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\01_Work\mall-admin-web\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\01_Work\mall-admin-web\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\01_Work\mall-admin-web\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\01_Work\mall-admin-web\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\01_Work\mall-admin-web\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\01_Work\mall-admin-web\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\01_Work\mall-admin-web\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\01_Work\mall-admin-web\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\01_Work\mall-admin-web\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\01_Work\mall-admin-web\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (E:\\01_Work\\mall-admin-web\\node_modules\\which\\which.js:13:12)\n    at F (E:\\01_Work\\mall-admin-we
b\\node_modules\\which\\which.js:68:19)\n    at E (E:\\01_Work\\mall-admin-web\\node_modules\\which\\which.js:80:29)\n    at E:\\01_Work\\mall-admin-web\\node_modules\\which\\which.js:89:16
\n    at E:\\01_Work\\mall-admin-web\\node_modules\\isexe\\index.js:42:5\n    at E:\\01_Work\\mall-admin-web\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:123:15
)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import sys; print "2.7.9
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 6.9.1
gyp verb command install [ '6.9.1' ]
gyp verb install input version string "6.9.1"
gyp verb install installing version: 6.9.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 6.9.1
gyp verb build dir attempting to create "build" dir: E:\01_Work\mall-admin-web\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? E:\01_Work\mall-admin-web\node_modules\node-sass\build
gyp verb Not using VS2017: Could not use PowerShell to find VS2017
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: E:\01_Work\mall-admin-web\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: E:\01_Work\mall-admin-web\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: E:\01_Work\mall-admin-web\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'E:\\01_Work\\mall-admin-web\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\01_Work\\mall-admin-web\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\01_Work\\mall-admin-web\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\lenovo\\.node-gyp\\6.9.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\lenovo\\.node-gyp\\6.9.1',
gyp info spawn args   '-Dnode_gyp_dir=E:\\01_Work\\mall-admin-web\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\lenovo\\.node-gyp\\6.9.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\01_Work\\mall-admin-web\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\01_Work\\mall-admin-web\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "E:\01_Work\mall-admin-web\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "E:\01_Work\mall-admin-web\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "E:\01_Work\mall-admin-web\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "E:\01_Work\mall-admin-web\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "E:\01_Work\mall-admin-web\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2004, in GenerateOutput
    generator_flags))
  File "E:\01_Work\mall-admin-web\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 943, in _GenerateProject
    return _GenerateMSVSProject(project, options, version, generator_flags)
  File "E:\01_Work\mall-admin-web\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1047, in _GenerateMSVSProject
    p.WriteIfChanged()
  File "E:\01_Work\mall-admin-web\node_modules\node-gyp\gyp\pylib\gyp\MSVSProject.py", line 208, in WriteIfChanged
    encoding="Windows-1252")
  File "E:\01_Work\mall-admin-web\node_modules\node-gyp\gyp\pylib\gyp\easy_xml.py", line 122, in WriteXmlIfChanged
    xml_string = xml_string.decode(default_encoding).encode(encoding)
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 6991-6994: character maps to <undefined>
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (E:\01_Work\mall-admin-web\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "E:\\01_Work\\01_DevSpace\\nodes\\nodejs\\node.exe" "E:\\01_Work\\mall-admin-web\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "-
-libsass_library="
gyp ERR! cwd E:\01_Work\mall-admin-web\node_modules\node-sass
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN v-charts@1.19.0 requires a peer of echarts@>3.0.0 but none was installed.
npm WARN echarts-liquidfill@2.0.4 requires a peer of echarts@^4.1.0 but none was installed.
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none was installed.
npm WARN Error: EPERM: operation not permitted, scandir 'E:\01_Work\mall-admin-web\node_modules\har-validator\node_modules'
npm WARN     at Error (native)
npm WARN  { Error: EPERM: operation not permitted, scandir 'E:\01_Work\mall-admin-web\node_modules\har-validator\node_modules'
npm WARN     at Error (native)
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'E:\\01_Work\\mall-admin-web\\node_modules\\har-validator\\node_modules' }
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "E:\\01_Work\\01_DevSpace\\nodes\\nodejs\\node.exe" "E:\\01_Work\\01_DevSpace\\nodes\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\01_Work\mall-admin-web\npm-debug.log

**Comment by kyne0116** [comment]
问题已解决，首先确保npm和node更新到最新，其次是windows平台缺少编译环境
1、先运行： npm install -g node-gyp 
2、然后运行：运行 npm install –global –production windows-build-tools 可以自动安装跨平台的编译器：gym
